version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "meal-calculate-task"
          ContainerPort: 8000
        PlatformVersion: "LATEST"
